services:
  - type: web
    name: simple-mern-app
    env: node
    buildCommand: npm install && cd server && npm install && cd ../client && npm install && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
